version: '3.8'

services:
  mlflow:
    build:
      context: .
      dockerfile: mlflow.dockerfile
    ports:
      - "5000:5000"
    volumes:
      - "${PWD}/mlflow_data:/home/mlflow_data"
    environment:
      - MLFLOW_TRACKING_URI=http://0.0.0.0:5000
